//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `DeckList`.
    static let deckList = _R.storyboard.deckList()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "DeckList", bundle: ...)`
    static func deckList(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.deckList)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 5 localization keys.
    struct localizable {
      /// Value: Cancel
      static let cancel = Rswift.StringResource(key: "cancel", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Continue
      static let `continue` = Rswift.StringResource(key: "continue", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: MTG URL
      static let deck_list_alert_textfield_placeholder = Rswift.StringResource(key: "deck_list_alert_textfield_placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: New Deck List
      static let deck_list_alert_title = Rswift.StringResource(key: "deck_list_alert_title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: We support deck lists urls from: Tappedout, MTGGoldfish and LigaMagic. Just paste the Url from one of this sites to download it
      static let deck_list_alert_message = Rswift.StringResource(key: "deck_list_alert_message", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Cancel
      static func cancel(_: Void = ()) -> String {
        return NSLocalizedString("cancel", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Continue
      static func `continue`(_: Void = ()) -> String {
        return NSLocalizedString("continue", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: MTG URL
      static func deck_list_alert_textfield_placeholder(_: Void = ()) -> String {
        return NSLocalizedString("deck_list_alert_textfield_placeholder", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: New Deck List
      static func deck_list_alert_title(_: Void = ()) -> String {
        return NSLocalizedString("deck_list_alert_title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: We support deck lists urls from: Tappedout, MTGGoldfish and LigaMagic. Just paste the Url from one of this sites to download it
      static func deck_list_alert_message(_: Void = ()) -> String {
        return NSLocalizedString("deck_list_alert_message", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try deckList.validate()
    }
    
    struct deckList: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let deckListView = StoryboardViewControllerResource<DeckListView>(identifier: "DeckListView")
      let name = "DeckList"
      
      func deckListView(_: Void = ()) -> DeckListView? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: deckListView)
      }
      
      static func validate() throws {
        if _R.storyboard.deckList().deckListView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'deckListView' could not be loaded from storyboard 'DeckList' as 'DeckListView'.") }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = ViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
